### PR TITLE
Sanitize names that must follow DNS naming rules

### LINKED ISSUE #466: CR "metadata.name" invalid format should throw exception on the user console
When a user supplies unsupported `metadata.name` Jaeger operator should throw an exception on user console.

```
$ oc create -f jaeger-services-final.yaml 
jaeger.jaegertracing.io/jaegerqe.test created
```

Current flow: 
* deploys ES cluster 
* try to deploy jaeger services(throws an exception on the jaeger-operator log)

Expected flow:
* validate CR file
* continue to deploy if the user supplied a valid CR file.

Operator log: [jaeger-operator-545c69455d-j7zjg.log](https://github.com/jaegertracing/jaeger-operator/files/3264602/jaeger-operator-545c69455d-j7zjg.log)

CR file:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: "jaegerqe.test"
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.12
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 1
        queue-size: 20000
      es:
        bulk:
          size: 524288
          workers: 1
          flush-interval: 200ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.12
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.12
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 10000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes #466 by making the sanitizing names for services and volumes, to be DNS-compliant. Apart from this change, a name such as `jaegerqe.test` is now possible and yields no errors.

The bigger topic of "validation" in general isn't being touched by this PR. 

cc @jkandasa 

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jkandasa** [comment]
@jpkrohling We should document this approach on a notable area. Otherwise, the end user will be waiting for a given name, but Jaeger-operator creates a different name (if the name contains invalid chars).

**Comment by jpkrohling** [comment]
+1 , but note that we only change service names and volume names, both are what I'd consider implementation details.

**Comment by jpkrohling** [comment]
By the way: our readme is already somewhat crowded. I'm actually not sure this belongs to the main documentation.

@jstickler, any ideas?

File: pkg/util/dns_name.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+	"regexp"
+	"strings"
+	"unicode/utf8"
+)
+
+// DNSName returns a dns-safe string for the given name.
+// Any char that is not [a-z0-9] is replaced by "-".
+// If the final name starts with "-", "a" is added as prefix. Similarly, if it ends with "-", "z" is added.
+func DNSName(name string) string {
+	var regex = regexp.MustCompile(`[a-z0-9]`)
```
Comment (objectiser) [inline pkg/util/dns_name.go]: This would be better defined once outside the function.

File: pkg/util/dns_name_test.go [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+func TestDnsName(t *testing.T) {
+	var tests = []struct {
+		in  string
+		out string
+	}{
+		{"simplest", "simplest"},
+		{"instance.with.dots-collector-headless", "instance-with-dots-collector-headless"},
+		{"TestQueryDottedServiceName.With.Dots", "testquerydottedservicename-with-dots"},
+		{"Service🦄", "service-z"},
```
Comment (objectiser) [inline pkg/util/dns_name_test.go]: Need a test for symbol at start.

**Comment by JStickler** [comment]
@jpkrohling Yes, the operator README is really long (14 pages if I was going to print it).  But it's not part of this PR, and I'm not sure what you were getting at in your question to me?  Could you clarify what you wanted my opinion on?

**Comment by jpkrohling** [comment]
@JStickler sorry, I kinda forgot to add the context :-) The change from this PR introduces a change that needs to be documented: if the Jaeger `CustomResource` contains chars not compatible with the specification for DNS names, the invalid chars are replaced by "-" on object names that need to follow this rule (such as "services" and "volumes").

IMO, this is too specific to be useful in the readme, but I can imagine that users might be confused when they create a Jaeger instance named `jaeger.testqe` and their service names are all like `jaeger-testqe`.

**Comment by jpkrohling** [comment]
I'm merging, but will work on the documentation based on what @JStickler suggests.
