### PR TITLE
Make sure to call ctx.cleanup if prepare() fails

### LINKED ISSUE #388: e2e tests don't clean up if they fail during operator deploy
If an e2e tests fails because the operator does not deploy during the prepare call, context.cleanup will not be called, and therefore the namespace that was created will not be deleted.

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

This fixed #388   Currently if tests fail during the prepare() call ctx.cleanup() will not be called and the namespace created for the test does not get cleaned up.

### CODE REVIEW

File: test/e2e/cassandra.go [hunk 1]
```diff
@@ -15,7 +16,11 @@ import (
 
 // Cassandra runs a test with Cassandra as the backing storage
 func Cassandra(t *testing.T) {
-	ctx := prepare(t)
+	ctx, err := prepare(t)
```
Comment (pavolloffay) [inline test/e2e/cassandra.go]: Could we call `prepare` in the caller so each test would not have to repeat this block?

Comment (kevinearls) [reply test/e2e/cassandra.go]: @pavolloffay Once I finish the other changes I am making for reporting it will be called in the Setup method, only once per suite.  https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/all_in_one_test.go#L36-L44

I've run into this bug a few times though, so I wanted to get this done first.

**Comment by kevinearls** [comment]
@pavolloffay @objectiser @jpkrohling  Please review.
