### PR TITLE
Fix override storage and ingress values when upgrade to 1.22

### LINKED ISSUE #1437: When migrating from operator 1.21.3 to 1.22.1 values in storage/options are lost for existing Jaeger instances
I've upgraded from operator v1.21.3 to 1.22.1 and afterwards the existing Jaeger instances were migrated from v1.21.0 to v.1.22.0. However Jaeger pods started going into a crash loop as they could not connect to our Elastic instance anymore. Turns out the settings in the Jaeger instances under storage/options were removed by the operator on upgrade. Redeploying the Jaeger configuration fixed the issue but the operator should not have cleared the settings in the first place.

I've reproduced this by deploying the v1.21.3 operator in an empty k8s cluster and deploying the following jaeger instance:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: twd
spec:
  storage:
    options:
      es:
        server-urls: https://example:9200
  ingress:
    enabled: false
```

Before the upgrade to v1.22.1 this looked like this in k8s:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: jaeger-operator.jaeger-operator
  name: twd
  namespace: default
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    options: {}
    resources: {}
  collector:
    config: {}
    options: {}
    resources: {}
  ingester:
    config: {}
    options: {}
    resources: {}
  ingress:
    enabled: false
    openshift: {}
    options: {}
    resources: {}
    security: none
  query:
    options: {}
    resources: {}
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    options:
      es:
        server-urls: https://example:9200
    type: memory
  strategy: allinone
  ui:
    options: {}
status:
  phase: Running
  version: 1.21.0
```

After the upgrade of the operator to v1.22.1 this same Jaeger instance looked like this:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: jaeger-operator.jaeger-operator
  name: twd
  namespace: default
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    options: {}
    resources: {}
  collector:
    config: {}
    options: {}
    resources: {}
  ingester:
    config: {}
    options: {}
    resources: {}
  ingress:
    enabled: false
    openshift: {}
    options: {}
    resources: {}
    security: none
  query:
    options: {}
    resources: {}
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    options: {}
    type: memory
  strategy: allinone
  ui:
    options: {}
status:
  phase: Running
  version: 1.22.0
```

As you can see the values set in storage/options are lost.

### PR DESCRIPTION
**Pull request by rubenvp8510**
This Fixes #1437 

Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

### CODE REVIEW

File: pkg/upgrade/v1_22_0_test.go [hunk 1]
```diff
@@ -20,12 +20,17 @@ func TestUpgradeJaegerTagssv1_22_0(t *testing.T) {
...
+		"server-urls": "https://example:9200",
+	})
+
 	nsn := types.NamespacedName{Name: "my-instance"}
 	existing := v1.NewJaeger(nsn)
 	existing.Status.Version = "1.21.0"
 	existing.Spec.AllInOne.Options = opts
 	existing.Spec.Agent.Options = opts
 	existing.Spec.Collector.Options = opts
+	existing.Spec.Storage.Options = storageOpts
```
Comment (jpkrohling) [inline pkg/upgrade/v1_22_0_test.go:33]: Add the Ingress as well, given that there was a bug with it too.

Comment (rubenvp8510) [reply pkg/upgrade/v1_22_0_test.go:37]: Done!

**Review by jpkrohling — APPROVED** [review]
