### PR TITLE
Get rid of finalizer, clean sidecars when no jaeger instance found

### LINKED ISSUE #568: Finalizer blocks the deletion of CRs if the operator isn't running
A side effect of adding a finalizer to the Jaeger CRs is that the same operator instance that created the CR has to be running when the CR is deleted, otherwise the `kubectl delete` command blocks indefinitely and will end up not removing the CR:

How to reproduce:

In the first console:
```console
$ make run
INFO[0000] Versions                                      arch=amd64 jaeger=1.13.1 jaeger-operator=v1.13.1-36-g5ade023b operator-sdk=v0.8.1 os=linux version=go1.12.5
INFO[0000] Auto-detected the platform                    platform=kubernetes
INFO[0000] Automatically adjusted the 'es-provision' flag  es-provision=false
INFO[0000] The service account running this operator has the role 'system:auth-delegator', enabling OAuth Proxy's 'delegate-urls' option 
```

In a second console:
```console
$ kubectl apply -f /tmp/simplest.yaml 
jaeger.jaegertracing.io/simplest2 created
$ kubectl get jaegers
NAME        AGE
simplest2   9s
```

Then kill the operator from the first console. On the second console:

```console
$ kubectl delete jaeger simplest2
jaeger.jaegertracing.io "simplest2" deleted
^C
$ kubectl get jaegers
NAME        AGE
simplest2   102s
```

cc @rubenvp8510

### PR DESCRIPTION
**Pull request by rubenvp8510**
@jpkrohling 

After thinking about it, it seems like we don't need the finalizer, the thing with the finalizer is that the finalizer give you access to the jaeger instance before k8 deletes it. here I only need the name at the reconciliation request to do the clean of the sidecars.

Fixes #568

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@jpkrohling @pavolloffay  I changed this to use auto-detect feature, please review when you get a chance

File: pkg/autodetect/main.go [hunk 1]
```diff
@@ -79,6 +81,11 @@ func (b *Background) autoDetectCapabilities() {
 	}
 
 	b.detectClusterRoles()
+	if err := b.cleanDeployments(); err != nil {
+		log.WithFields(log.Fields{
+			"error": err,
+		}).Errorf("Error cleaning orphaned deployment")
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: `s/Error/error/`
`s/deployment/deployments/`, but I think the method should not fail, just like the other `detect` methods. Instead, log the specific messages within the `cleanDeployments` function.

File: pkg/autodetect/main.go [hunk 2]
```diff
@@ -147,6 +154,41 @@ func (b *Background) detectClusterRoles() {
...
 
+func (b *Background) cleanDeployments() error {
+	log.Info("Detecting orphaned deployments.")
+	deployments := &appsv1.DeploymentList{}
+	opts := &client.ListOptions{}
+	instances := &v1.JaegerList{}
+
+	// get all deployments
+	if err := b.cl.List(context.Background(), opts, deployments); err != nil {
+		return err
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: Related to the previous comment: log the message here, and `return` (without an error).

File: pkg/autodetect/main.go [hunk 3]
```diff
@@ -147,6 +154,41 @@ func (b *Background) detectClusterRoles() {
 	}
 }
 
+func (b *Background) cleanDeployments() error {
+	log.Info("Detecting orphaned deployments.")
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: `s/log.Info/log.Debug/`

File: pkg/autodetect/main.go [hunk 4]
```diff
@@ -147,6 +154,41 @@ func (b *Background) detectClusterRoles() {
...
+	opts := &client.ListOptions{}
+	instances := &v1.JaegerList{}
+
+	// get all deployments
+	if err := b.cl.List(context.Background(), opts, deployments); err != nil {
+		return err
+	}
+
+	// get all jaeger instances
+	if err := b.cl.List(context.Background(), opts, instances); err != nil {
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: Are we able to get *only* the deployment name+namespace and the annotations, instead of the full objects? I'm afraid we could be causing unnecessary load on the cluster by retrieving all *deployments* from all namespaces that this operator has access to.

@jkandasa, @kevinearls: could you add a case for your test plans? It would be good to test how the operator behaves when there are 100/1.000/10.000 deployments in the cluster.

File: pkg/autodetect/main.go [hunk 5]
```diff
@@ -147,6 +154,41 @@ func (b *Background) detectClusterRoles() {
...
+	for _, dep := range deployments.Items {
+		if _, ok := dep.Annotations[inject.Annotation]; ok {
+			jaeger := inject.Select(&dep, instances)
+			if jaeger == nil { // Jaeger instance not exist anymore, we need to clean this up.
+				inject.CleanSidecar(&dep)
+				if err := b.cl.Update(context.Background(), &dep); err != nil {
+					log.WithFields(log.Fields{
+						"deploymentName":      dep.Name,
+						"deploymentNamespace": dep.Namespace,
+					}).Error(err)
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: Looks like it's missing the actual log message? :) 

`.Info("failed to clean sidecar")`

File: pkg/autodetect/main.go [hunk 6]
```diff
@@ -147,6 +154,41 @@ func (b *Background) detectClusterRoles() {
...
+	// get all deployments
+	if err := b.cl.List(context.Background(), opts, deployments); err != nil {
+		return err
+	}
+
+	// get all jaeger instances
+	if err := b.cl.List(context.Background(), opts, instances); err != nil {
+		return err
+	}
+	log.Info(len(deployments.Items))
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: Left over from local tests?

File: pkg/autodetect/main.go (hunk 4 above)
Comment (kevinearls) [reply pkg/autodetect/main.go]: @jpkrohling Sure, a test case would be great.  The best thing to do would be create a ticket and assign it to me.  That way I'll be sure not to lose track of it...

Comment (heisenberg8510) [reply pkg/autodetect/main.go]: @jpkrohling I haven't found a way to get only the name and annotations, I did some modifications, I'm using LabelSelector to get the deployments already labeled by the operator.

Comment (rubenvp8510) [reply pkg/autodetect/main.go]: @jpkrohling I haven't found a way to get only the name and annotations, I did some modifications, I'm using LabelSelector to get the deployments already labeled by the operator. That could help to mitigate performance issues.

File: pkg/autodetect/main.go [hunk 7]
```diff
@@ -147,6 +151,44 @@ func (b *Background) detectClusterRoles() {
...
 
+func (b *Background) cleanDeployments() {
+	log.Debug("detecting orphaned deployments.")
+	deployments := &appsv1.DeploymentList{}
+	deployOpts := &client.ListOptions{}
+	jaegerOpts := &client.ListOptions{}
+	instances := &v1.JaegerList{}
+
+	// Only select fields that have the label 'sidecar.jaegertracing.io/inject'
+	if err := deployOpts.SetLabelSelector(inject.Annotation); err != nil {
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: Is this actually working? I thought we had an annotation, not a label.

File: pkg/autodetect/main.go [hunk 8]
```diff
@@ -147,6 +151,44 @@ func (b *Background) detectClusterRoles() {
...
+		log.WithError(err).Error("")
+	}
+
+	if err := b.cl.List(context.Background(), deployOpts, deployments); err != nil {
+		log.WithError(err).Error("Error cleaning orphaned deployment")
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: `s/Error cleaning/error cleaning/`

File: pkg/autodetect/main.go [hunk 9]
```diff
@@ -147,6 +151,44 @@ func (b *Background) detectClusterRoles() {
...
+	}
+
+	// get all jaeger instances
+	if err := b.cl.List(context.Background(), jaegerOpts, instances); err != nil {
+		log.WithError(err).Error("Error cleaning orphaned deployment")
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: `s/Error cleaning/error cleaning/`

File: pkg/autodetect/main.go [hunk 10]
```diff
@@ -147,6 +151,44 @@ func (b *Background) detectClusterRoles() {
...
+	for _, dep := range deployments.Items {
+		if _, ok := dep.Annotations[inject.Annotation]; ok {
+			jaeger := inject.Select(&dep, instances)
+			if jaeger == nil { // Jaeger instance not exist anymore, we need to clean this up.
+				inject.CleanSidecar(&dep)
+				if err := b.cl.Update(context.Background(), &dep); err != nil {
+					log.WithFields(log.Fields{
+						"deploymentName":      dep.Name,
+						"deploymentNamespace": dep.Namespace,
+					}).WithError(err).Error("Error cleaning orphaned deployment")
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: `s/Error cleaning/error cleaning/`

File: pkg/autodetect/main.go [hunk 11]
```diff
@@ -147,6 +151,44 @@ func (b *Background) detectClusterRoles() {
...
+	}
+
+	// get all jaeger instances
+	if err := b.cl.List(context.Background(), jaegerOpts, instances); err != nil {
+		log.WithError(err).Error("Error cleaning orphaned deployment")
+	}
+
+	// check deployments to see which one needs to be cleaned.
+	for _, dep := range deployments.Items {
+		if _, ok := dep.Annotations[inject.Annotation]; ok {
```
Comment (jpkrohling) [inline pkg/autodetect/main.go]: IIRC, we replace the value of the annotation to include the instance name. If you store the Jaeger instances in a map indexed by the name, you can check whether the instance is in the map, instead of running the `#Select` logic.

File: pkg/autodetect/main.go (hunk 4 above)
Comment (jpkrohling) [reply pkg/autodetect/main.go]: #584 created.

File: pkg/autodetect/main.go (hunk 7 above)
Comment (rubenvp8510) [reply pkg/autodetect/main.go]: Yes it works, I introduced a change to label the injected depolyments on the original PR when I used finalizers. 

https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/inject/sidecar.go#L47

File: pkg/autodetect/main.go (hunk 11 above)
Comment (rubenvp8510) [reply pkg/autodetect/main.go]: True! I thought we preserve the true/false in case of one jaeger instance OR the name, but you're right, that value is replaced by the instance name for all cases!

I've already done the change

File: pkg/autodetect/main.go (hunk 7 above)
Comment (jpkrohling) [reply pkg/autodetect/main.go]: Alright, sounds good. I think we kinda talked about this before, but let me cc @objectiser and @pavolloffay , as they might not be aware of this change.

@pavolloffay, @objectiser, TL;DR: we used to place the inject annotation under `annotations`, but we are now placing it under `labels`. The good thing is that we can now query deployments by the Jaeger Operator they are using (or simply by the existence of the label, like it's the case here). The downside is that we now have both an annotation (added by users) and a label (set by the operator).

**Comment by objectiser** [comment]
@rubenvp8510 @jpkrohling What abiout changing the label to "..../injected" (i.e. a status) - to distinguish it from the user provided annotation which is more like an instruction (e.g. "..../inject").

**Comment by rubenvp8510** [comment]
Not reached the target coverage due error handling parts :(

**Comment by rubenvp8510** [comment]
Any other required change here? :)

**Comment by jpkrohling** [comment]
Just merged :-) Thanks, @rubenvp8510!
