### PR TITLE
Changed to always use namespace when a name is involved

### LINKED ISSUE #285: Unable to create jaeger with the same name in different namespace
I was unable to create jaeger with the same name in a different namespace.

To reproduce
```
minishift v1.31.0+cfc599c
make run WATCH_NAMESPACE=""
```

create simples example in two namespaces

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #285 by using namespaces whenever a name is involved. Before this change, deploying a Jaeger instance in a namespace `tenant2` when there's already a Jaeger instance in another namespace (`tenant1`) would cause the underlying objects, such as `Deployment` objects, to be removed in favor of the one in the new namespace.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@jkandasa , this can be tested as follows:

```console
# make sure the environment is clean:
$ kubectl get deployments --all-namespaces
NAMESPACE     NAME                       READY     UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns                    2/2       2            2           28h
kube-system   default-http-backend       1/1       1            1           28h
kube-system   kubernetes-dashboard       1/1       1            1           28h
kube-system   nginx-ingress-controller   1/1       1            1           28h

$ kubectl create namespace tenant1
namespace/tenant1 created
$ kubectl create namespace tenant2
namespace/tenant2 created
$ kubectl apply -n tenant1 -f deploy/examples/simplest.yaml 
jaeger.jaegertracing.io/simplest created
$ kubectl apply -n tenant2 -f deploy/examples/simplest.yaml 
jaeger.jaegertracing.io/simplest created
$ kubectl get deployments -n tenant1
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
simplest   1/1       1            1           40s
$ kubectl get deployments -n tenant2
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
simplest   1/1       1            1           28s
$ kubectl get jaegers --all-namespaces
NAMESPACE   NAME       AGE
tenant1     simplest   51s
tenant2     simplest   38s

```

File: pkg/controller/jaeger/account.go [hunk 1]
```diff
@@ -3,15 +3,16 @@ package jaeger
...
 	"sigs.k8s.io/controller-runtime/pkg/client"
 
-	"github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1"
+	v1 "github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1"
 	"github.com/jaegertracing/jaeger-operator/pkg/inventory"
 )
 
 func (r *ReconcileJaeger) applyAccounts(jaeger v1.Jaeger, desired []corev1.ServiceAccount) error {
-	opts := client.MatchingLabels(map[string]string{
+	opts := client.InNamespace(jaeger.Namespace).MatchingLabels(map[string]string{
```
Comment (jpkrohling) [inline pkg/controller/jaeger/account.go]: This (and similar changes in the other `controller` functions) is the actual fix for the reported problem. All other changes are either to make the test more accurate, or to properly log what's going on.

File: pkg/controller/jaeger/account.go [hunk 2]
```diff
@@ -22,21 +23,30 @@ func (r *ReconcileJaeger) applyAccounts(jaeger v1.Jaeger, desired []corev1.Servi
...
+			"namespace": d.Namespace,
+		}).Debug("updating service account")
 		if err := r.client.Update(context.Background(), &d); err != nil {
 			return err
 		}
 	}
 
 	for _, d := range inv.Delete {
-		jaeger.Logger().WithField("account", d.Name).Debug("deleting service account")
+		jaeger.Logger().WithFields(log.Fields{
```
Comment (jpkrohling) [inline pkg/controller/jaeger/account.go]: This overrides the namespace from the `jaeger.Logger()`. Before this change, the log would say that it "deleting service account" in namespace `tenant1` when in fact the SA was in the namespace `tenant2`.

File: pkg/inventory/account.go [hunk 3]
```diff
@@ -54,7 +56,7 @@ func ForAccounts(existing []v1.ServiceAccount, desired []v1.ServiceAccount) Acco
 func accountMap(deps []v1.ServiceAccount) map[string]v1.ServiceAccount {
 	m := map[string]v1.ServiceAccount{}
 	for _, d := range deps {
-		m[d.Name] = d
+		m[fmt.Sprintf("%s.%s", d.Namespace, d.Name)] = d
```
Comment (jpkrohling) [inline pkg/inventory/account.go]: This kind of change isn't strictly required, as the data it receives *should* be part of the same namespace. However, it's more accurate to use the namespace in the key, as "tenant1.simplest" shouldn't be seen as the same as "tenant2.simplest". This fix helped me spot the real cause for the bug.

**Comment by jpkrohling** [comment]
@objectiser sorry for such a bit PR. Most of it are changes to the `NewJaeger` function, affecting pretty much all tests. I left comments in the important parts.

**Comment by jkandasa** [comment]
@jpkrohling can you provide a docker image for this PR?

File: pkg/controller/jaeger/deployment_test.go [hunk 4]
```diff
@@ -195,3 +200,60 @@ func TestDeploymentDeleteAfterCreate(t *testing.T) {
 	assert.Error(t, cl.Get(context.Background(), types.NamespacedName{Name: depToDelete.Name, Namespace: depToDelete.Namespace}, persistedDelete))
 	assert.Empty(t, persistedDelete.Name)
 }
+
+func TestDeploymentCreateExistingNameInAnotherNamespace(t *testing.T) {
+	// prepare
+	nsn := types.NamespacedName{
+		Name:      "TestDeploymentCreate",
```
Comment (objectiser) [inline pkg/controller/jaeger/deployment_test.go]: nit: test name

File: pkg/controller/jaeger/elasticsearch_test.go [hunk 5]
```diff
@@ -139,3 +139,63 @@ func TestElasticsearchesDelete(t *testing.T) {
...
 	assert.Error(t, err) // not found
 }
+
+func TestElasticsearchesCreateExistingNameInAnotherNamespace(t *testing.T) {
+	// prepare
+	viper.Set("es-provision", v1.FlagProvisionElasticsearchTrue)
+	defer viper.Reset()
+
+	nsn := types.NamespacedName{
+		Name:      "TestDaemonSetsCreateExistingNameInAnotherNamespace",
```
Comment (objectiser) [inline pkg/controller/jaeger/elasticsearch_test.go]: Nit: wrong test name

File: pkg/inventory/account_test.go [hunk 6]
```diff
@@ -50,3 +50,24 @@ func TestAccountInventory(t *testing.T) {
...
+	}, {
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      "to-create",
+			Namespace: "tenant2",
+		},
+	}}
+
+	inv := ForAccounts([]v1.ServiceAccount{}, create)
+	assert.Len(t, inv.Create, 2)
+	assert.Contains(t, create, create[0])
```
Comment (objectiser) [inline pkg/inventory/account_test.go]: Should this be testing `inv.Create [0]`?

File: pkg/inventory/configmap_test.go [hunk 7]
```diff
@@ -52,3 +52,24 @@ func TestConfigMapInventory(t *testing.T) {
...
+	}, {
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      "to-create",
+			Namespace: "tenant2",
+		},
+	}}
+
+	inv := ForConfigMaps([]v1.ConfigMap{}, create)
+	assert.Len(t, inv.Create, 2)
+	assert.Contains(t, create, create[0])
```
Comment (objectiser) [inline pkg/inventory/configmap_test.go]: Same here?

Comment (objectiser) [reply pkg/inventory/configmap_test.go]: If does need changing then same needs to be applied to similar patterns below.

File: pkg/inventory/account_test.go (hunk 6 above)
Comment (jpkrohling) [reply pkg/inventory/account_test.go]: Good catch. It should be `assert.Contains(t, inv.Create, create[0])`
