### PR TITLE
fix panic caused by an invalid type assertion

### LINKED ISSUE #1733: CRD validation does not catch invalid options
**Describe the bug**
Creating a Jaeger instance with Cassandra storage and setting an object as env key causes a panic.

**To Reproduce**
1. Add a Cassandra storage to a spec
2. Use an object as `ENV` key

**Expected behavior**
An error message when creating an instance with invalid parameters.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.28 and above
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
See: https://github.com/jaegertracing/jaeger-operator/issues/1649#issuecomment-1001271023

**Additional context**
See: https://github.com/jaegertracing/jaeger-operator/issues/1649

### PR DESCRIPTION
**Pull request by frzifus**
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>

Closes #1733 

## Which problem is this PR solving?
- option fields not of type string, [make the operator panic](https://github.com/jaegertracing/jaeger-operator/issues/1649#issuecomment-1001271023). 

## Short description of the changes
- Check type before making a type association in `(*Options).UnmarshalJSON` method.
- Return error if the elements of the argument list are not of type `string`.
- If `Options` cant be decoded [error 400](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/http_test.go#L78) is returned.

```bash
controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-jaegertracing-io-v1-jaeger", "UID": "6c77a050-a28d-4172-abc4-56f61670baef", "kind": "jaegertracing.io/v1, Kind=Jaeger", "resource": {"group":"jaegertracing.io","version":"v1","resource":"jaegers"}}
controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-jaegertracing-io-v1-jaeger", "code": 400, "reason": "", "UID": "6c77a050-a28d-4172-abc4-56f61670baef", "allowed": false}
```

### CODE REVIEW

File: apis/v1/options.go [hunk 1]
```diff
@@ -85,30 +87,43 @@ func (o Options) MarshalJSON() ([]byte, error) {
...
+			entries, err = entry(entries, fmt.Sprintf("%s.%v", key, k), v)
+			if err != nil {
+				return nil, err
+			}
 		}
-	case []interface{}:
-		values := make([]string, 0, len(value.([]interface{})))
-		for _, v := range value.([]interface{}) {
-			values = append(values, v.(string))
+	case []interface{}: // NOTE: explain why we dont look for []string
```
Comment (frzifus) [inline apis/v1/options.go:112]: wait i did that :o

**Review by rubenvp8510 — APPROVED** [review]

**Comment by pavolloffay** [comment]
Didn't we talk about using validating webhook to catch this?

File: apis/v1/options.go [hunk 2]
```diff
@@ -63,7 +63,9 @@ func (o *Options) UnmarshalJSON(b []byte) error {
 	if err := d.Decode(&entries); err != nil {
 		return err
 	}
-	o.parse(entries)
+	if err := o.parse(entries); err != nil {
+		return err
```
Comment (pavolloffay) [inline apis/v1/options.go:67]: is the return error propagated to the user at object creation?

**Comment by frzifus** [comment]
> Didn't we talk about using validating webhook to catch this?

@pavolloffay you are right. In course of doing this, i noticed that the `Jeager` object is already a unmarshalled version of the spec.

File: apis/v1/options.go (hunk 2 above)
Comment (frzifus) [reply apis/v1/options.go:67]: Not this particular one. But an error that says your body of your request is invalid.
Its the `"code": 400` in the webhook response.

Comment (pavolloffay) [reply apis/v1/options.go:67]: If the error is wrapped here would that be propagated to user? 

We should tell the user what was wrong in the CR if that is possible.

Comment (frzifus) [reply apis/v1/options.go:67]: oh seems i mixed things up. When you create Jeager with invalid `Options` it tells you whats wrong. 

```bash
$ k apply -f invalid.yaml                                                     
Error from server: error when creating "invalid.yaml": admission webhook "mjaeger.kb.io" denied the request: v1.Jaeger.Spec: v1.JaegerSpec.Strategy: Storage: v1.JaegerStorageSpec.Type: Options: unmarshalerDecoder: invalid option type, expect: string, got: map[string]interface {}, error found in #10 byte of ...|":"test"}},"type":"c|..., bigger context ...|"datacenter":"dev","enabled":false,"mode":"test"}},"type":"cassandra"},"strategy":"production"}}|...
```

Looking at the logs, we could explain error `400` a bit better. But placing a description in the  `"reason": ""` field needs to be done in `controller-runtime.webhook.webhooks`.
