### PR TITLE
Protect the platform behind a mutex

### LINKED ISSUE #1983: fatal error: concurrent map read and map write
**Describe the bug**
The error happens sometimes, i guess some process triggers that.
Please ignore `This field was missing!!!!!!!!` as it is our internal message.

Please find attached file with surrouding logs 

[On_demand_report_2022-07-05T10_54_28.180Z_d7538140-fc50-11ec-84ba-cf7f04fb0981.csv](https://github.com/jaegertracing/jaeger-operator/files/9045750/On_demand_report_2022-07-05T10_54_28.180Z_d7538140-fc50-11ec-84ba-cf7f04fb0981.csv)

### PR DESCRIPTION
**Pull request by iblancasa**
## Which problem is this PR solving?
- Continuation of #2276 to fix #1983

## Short description of the changes
- Added a new structure to manage the operator configuration
- Protect the Platform setting behind a mutex

Note: this work needs to be done for other settings too but will be done in follow-up PRs

### CODE REVIEW

**Review by rubenvp8510 — APPROVED** [review]

File: pkg/autodetect/main_test.go [hunk 1]
```diff
@@ -68,6 +68,9 @@ func TestStartContinuesInBackground(t *testing.T) {
 	}
 	b := WithClients(cl, dcl, cl)
 
+	fmt.Println(viper.IsSet("auth-delegator-available"))
+	fmt.Println(viper.GetBool("auth-delegator-available"))
```
Comment (frzifus) [inline pkg/autodetect/main_test.go:72]: Is that a debug leftover?
