### PR TITLE
Ensure oauth-proxy ImageStream is detected eventually

### LINKED ISSUE #2339: [Bug]: [OpenShift] oauth-proxy ImageStream not detect after operator startup
### What happened?

On OpenShift disconnected environments certain conditions cause the `detectOAuthProxyImageStream` function to fail at startup, e.g.:
 - shortly after SNO node reboot the Image API may not be available yet, preventing the function from reading the `dockerImageReference` from the ImageStream.
 - `oauth-proxy` ImageStream's `dockerReferenceImage` empty due to (temporary) pull failure during operator startup.

Once the operator has started, the detection never runs again. As a result the managed jaeger pod remains in ImagePullBackOff. A restart of the operator works around this, but that's not a viable option for managed/automated clusters.

### Steps to reproduce

1. deploy jaeger-operator on OpenShift
2. remove oauth-proxy imagestream (for the sake of reproducing)
3. verify oauth-proxy detection failed
4. csv recreates oauth-proxy imagestream
5. verify oauth-proxy imagestream is not detected and jaeger pods are in imagepullbackoff error

### Expected behavior

The operator should detect the oauth-image stream eventually, even after the initial detect loop fails due to external factors.

### Relevant log output

```shell
$ oc delete --wait=false is -n openshift oauth-proxy;oc delete pods --wait=false -n openshift-distributed-tracing -lname=jaeger-operator; oc delete pods -n istio-system -lapp=jaeger

$ oc logs -n openshift-distributed-tracing deployment/jaeger-operator|less
<...>
2023-10-10T08:16:47Z    ERROR   Failed to obtain OAuthProxy ImageStream {"namespace": "openshift", "name": "oauth-proxy", "error": "the cache is not started, can not read objects"}
github.com/jaegertracing/jaeger-operator/pkg/autodetect.(*Background).detectOAuthProxyImageStream
        /workspace/pkg/autodetect/main.go:264
github.com/jaegertracing/jaeger-operator/pkg/autodetect.(*Background).autoDetectCapabilities
        /workspace/pkg/autodetect/main.go:104
github.com/jaegertracing/jaeger-operator/pkg/autodetect.(*Background).Start
        /workspace/pkg/autodetect/main.go:70
github.com/jaegertracing/jaeger-operator/pkg/cmd/start.bootstrap
        /workspace/pkg/cmd/start/bootstrap.go:126
github.com/jaegertracing/jaeger-operator/pkg/cmd/start.start
        /workspace/pkg/cmd/start/main.go:72
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/jaegertracing/jaeger-operator/cmd.Execute
        /workspace/cmd/root.go:28
main.main
        /workspace/main.go:6
runtime.main
        /usr/local/go/src/runtime/proc.go:250
2023-10-10T08:16:47Z    INFO    Determining whether we should enable the Elasticsearch Operator integration
2023-10-10T08:16:47Z    INFO    Automatically adjusted the integration with the ES Operator     {"es-provision": "Yes"}
2023-10-10T08:16:47Z    INFO    Determining whether we should enable the Kafka Operator integration
2023-10-10T08:16:47Z    INFO    The service account running this operator has the role 'system:auth-delegator', enabling OAuth Proxy's 'delegate-urls' option
2023-10-10T08:16:47Z    INFO    finished the first auto-detection


$ oc get pods -n istio-system -lapp=jaeger
NAME                      READY   STATUS             RESTARTS   AGE
jaeger-676c7b8dbd-z4v54   1/2     ImagePullBackOff   0          4m12s
```

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

On OpenShift through OLM

### Deployment configs

_No response_

### PR DESCRIPTION
**Pull request by bverschueren**
## Which problem is this PR solving?
- Resolves #2339 

## Description of the changes
- move the detectOAuthProxyImageStream function out of `autoDetectCapabilities`'s `firstRun.Do` block
- introduce a check to prevent needless api calls if `openshift-oauth-proxy-image` is already digest-based (assuming detection has occurred)

## How was this change tested?
- patch jaeger csv with generated operator image and verified if `openshift-oauth-proxy-image` is updated after initial run fails

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: pkg/autodetect/main.go [hunk 1]
```diff
@@ -222,7 +222,7 @@ func (b *Background) detectOAuthProxyImageStream(ctx context.Context) {
 	ctx, span := tracer.Start(ctx, "detectOAuthProxyImageStream")
 	defer span.End()
 
-	if OperatorConfiguration.GetPlatform() == OpenShiftPlatform {
+	if OperatorConfiguration.GetPlatform() != OpenShiftPlatform {
```
Comment (iblancasa) [inline pkg/autodetect/main.go:225]: Good catch!

Comment (iblancasa) [inline pkg/autodetect/main.go:225]: Good catch!

File: pkg/autodetect/main.go [hunk 2]
```diff
@@ -96,12 +97,11 @@ func (b *Background) autoDetectCapabilities() {
 			// the platform won't change during the execution of the operator, need to run it only once
 			b.detectPlatform(ctx, apiList)
 
-			b.detectOAuthProxyImageStream(ctx)
-
 			// the version of the APIs provided by the platform will not change
 			b.detectCronjobsVersion(ctx)
 			b.detectAutoscalingVersion(ctx)
 		})
+		b.detectOAuthProxyImageStream(ctx)
```
Comment (iblancasa) [inline pkg/autodetect/main.go:104]: Since it seems that we need to rerun this multime times, we need to add new field and methods to the `OperatorConfiguration` struct to ensure we don't access `viper` concurrently at the same time.

File: pkg/autodetect/main.go [hunk 3]
```diff
@@ -240,13 +240,27 @@ func (b *Background) detectOAuthProxyImageStream(ctx context.Context) {
 		return
 	}
 
+	// if the image is already digest-based no need to get the reference from an ImageStream
+	currImage := viper.GetString("openshift-oauth-proxy-image")
```
Comment (iblancasa) [inline pkg/autodetect/main.go:244]: Nice change!

**Review by iblancasa — CHANGES_REQUESTED** [review]

File: pkg/autodetect/main.go (hunk 2 above)
Comment (bverschueren) [reply pkg/autodetect/main.go:104]: Thanks for that! I've added methods to protect access behind a mutex and moved the image name string into a global constant.

**Review by iblancasa — APPROVED** [review]
