### PR TITLE
fixes #1568 #2225

### LINKED ISSUE #1568: Facing issues in getting the IP address to access Jaeger-UI on Linux platform
**Describe the bug**

Hi Team, 

I am working on jaeger deployment using jaeger-operators on the Ubuntu Linux/AMD64 machine using minikube. 

I have followed the [docs](https://github.com/jaegertracing/jaeger-operator#getting-started), addon ingress to minikube, installed operator using given yaml files, and activated extra features. Then created the jaeger instance once jaeger-operator is ready with namespace ‘observability’, following the above linked documentation. 

Below is the output of `kubectl get all -n observability`: 
~~~ 
$ kubectl get all -n observability 

NAME                                 READY   STATUS    RESTARTS   AGE 
pod/jaeger-operator-dbf5767c-8dgjf   1/1     Running   0          92m 
pod/simplest-5675c68699-c7wgp        1/1     Running   0          89m   

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                  AGE 
service/jaeger-operator-metrics       ClusterIP   10.97.208.223   <none>        8383/TCP,8686/TCP                        92m 
service/simplest-agent                ClusterIP   None            <none>        5775/UDP,5778/TCP,6831/UDP,6832/UDP      89m 
service/simplest-collector            ClusterIP   10.99.48.59     <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   89m 
service/simplest-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   89m 
service/simplest-query                ClusterIP   10.104.172.28   <none>        16686/TCP,16685/TCP                      89m 

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE 
deployment.apps/jaeger-operator   1/1     1            1           92m 
deployment.apps/simplest          1/1     1            1           89m 

NAME                                       DESIRED   CURRENT   READY   AGE 
replicaset.apps/jaeger-operator-dbf5767c   1         1         1       92m 
replicaset.apps/simplest-5675c68699        1         1         1       89m 
~~~ 

However, I am not getting the value of address, where Jaeger-UI is available. Below is the ingress information: 
~~~ 
$ kubectl get -n observability ingress 

NAME             CLASS    HOSTS   ADDRESS   PORTS   AGE 
simplest-query   <none>   *                 80      25h 
~~~ 

I have verified that ingress is addon to minikube.  

Can you please provide some pointers on what could be the issue here?    

**To Reproduce**

I have exactly followed the [getting started](https://github.com/jaegertracing/jaeger-operator#getting-started) document.

**Expected behavior**

Ingress should serve the Jaeger-UI and IP address must be returned.

**Screenshots**

NA

**Version (please complete the following information):**

 - OS: Linux
 - Jaeger version: master branch
 - Deployment: minikube

**What troubleshooting steps did you try?**

Checked that ingress is addon to minikube.

**Additional context**

NA

### PR DESCRIPTION
**Pull request by antoniomerlin**
added function getIngressClass which set default or nginx ingress class to jaeger define ingress for providing loadbalancer IP.

## Which problem is this PR solving?
- Resolve #1568 #2225

## Description of the changes
- if spec.IngressClassName is not specified in CRD, then this will query kubernetes API for getting list of IngressClasses and look for if any default IngressClass is available, if present the it attach that IngressClass to networkingv1.IngressSpec of jaegerIngress and if not available then it check for nginx ingress controller and attach that and if nothing is avalable then it do nothing.

## How was this change tested?
- local multinode cluster with ngnix as ingress controller

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by iblancasa — CHANGES_REQUESTED** [review]
Please, add a test for this.

**Review by iblancasa — CHANGES_REQUESTED** [review]
Please, add a test for this.

**Comment by antoniomerlin** [comment]
Hi, thanks for reviewing, i've modified the changes just a query you already having test mentioning this scenario :-
```
func TestQueryIngressClass(t *testing.T) {
	jaeger := v1.NewJaeger(types.NamespacedName{Name: "TestQueryIngressClass"})
	jaegerNoIngressNoClass := v1.NewJaeger(types.NamespacedName{Name: "TestQueryIngressNoClass"})

	inressClassName := "nginx"
	jaeger.Spec.Ingress.IngressClassName = &inressClassName

	ingress := NewQueryIngress(jaeger)
	ingressNoClass := NewQueryIngress(jaegerNoIngressNoClass)

	dep := ingress.Get()

	assert.NotNil(t, dep.Spec.IngressClassName)
	assert.Equal(t, "nginx", *dep.Spec.IngressClassName)
	assert.Nil(t, ingressNoClass.Get().Spec.IngressClassName)
}
```
```pkg/ingress/query_test.go``` do i need to write again or can use existing one or do any modification in this ?

**Comment by iblancasa** [comment]
> `pkg/ingress/query_test.go` do i need to write again or can use existing one or do any modification in this ?

You can complete that test to set a custom value and check if the custom value is properly set.

**Comment by antoniomerlin** [comment]
> > `pkg/ingress/query_test.go` do i need to write again or can use existing one or do any modification in this ?
> 
> You can complete that test to set a custom value and check if the custom value is properly set.

okay thanks.

File: pkg/ingress/query.go [hunk 1]
```diff
@@ -150,3 +158,41 @@ func getRule(host string, path string, pathType *networkingv1.PathType, backend
 	}
 	return rule
 }
+
+func getIngressClass() (string, bool) {
+	ingressClass := ""
+	nginxIngressAvailable := false
+	// This statement only work if it is running inside cluster, if you want to test outside replace this statement with
+	// config, err := clientcmd.BuildConfigFromFlags("", "PATH_TO_YOUR_CLUSTER_CONFIG_FILE")
```
Comment (iblancasa) [inline pkg/ingress/query.go:166]: This comment is not needed because it doesn't make sense to run this application outside a cluster of without being connected to one.

File: pkg/ingress/query.go [hunk 2]
```diff
@@ -150,3 +158,41 @@ func getRule(host string, path string, pathType *networkingv1.PathType, backend
 	}
 	return rule
 }
+
+func getIngressClass() (string, bool) {
```
Comment (iblancasa) [inline pkg/ingress/query.go:162]: Could you add a test for this method?

Comment (iblancasa) [reply pkg/ingress/query.go:162]: This method is to get the default Ingress class.
```suggestion
func getDefaultIngressClass() (string, bool) {
```

File: pkg/ingress/query.go [hunk 3]
```diff
@@ -150,3 +158,41 @@ func getRule(host string, path string, pathType *networkingv1.PathType, backend
...
+				}
+			}
+		}
+	}
+	if len(ingressClass) > 0 {
+		return ingressClass, false
+	} else if nginxIngressAvailable {
+		return "nginx", false
+	}
+	return "", true
```
Comment (iblancasa) [inline pkg/ingress/query.go:197]: Shouldn't this be `false`?

File: pkg/ingress/query_test.go [hunk 4]
```diff
@@ -287,7 +287,13 @@ func TestQueryIngressClass(t *testing.T) {
 
 	assert.NotNil(t, dep.Spec.IngressClassName)
 	assert.Equal(t, "nginx", *dep.Spec.IngressClassName)
-	assert.Nil(t, ingressNoClass.Get().Spec.IngressClassName)
+	_, err := getIngressClass()
```
Comment (iblancasa) [inline pkg/ingress/query_test.go:290]: Create a separate test for this method.

Also, in this test, you should test:
1. What does it happen when you don't provide an Ingress class in a Jaeger instance and there is a default Ingress class in the cluster?
1. What does it happen when you provide an Ingress class in a Jaeger instance and there is a default Ingress class in the cluster?

**Review by iblancasa — CHANGES_REQUESTED** [review]

File: pkg/ingress/query.go (hunk 2 above)
Comment (antoniomerlin) [reply pkg/ingress/query.go:162]: Hi, actually this method provide default ingressClass if that ingress controller is set to default, if there is no default ingress controller is there then ,it look for nginx ingress controller if available then it add that to jaeger ingress.

File: pkg/ingress/query.go (hunk 3 above)
Comment (antoniomerlin) [reply pkg/ingress/query.go:197]: This is if there is neither default ingress controller is there nor nginx ingress controller available.

File: pkg/ingress/query_test.go (hunk 4 above)
Comment (antoniomerlin) [reply pkg/ingress/query_test.go:290]: And in this do i need to add 3rd case 
3. What happen if you don't provide an Ingress class in a Jaeger instance and there is no default Ingress class in the cluster but there is nginx ingress controller available in cluster. (as in this case issue #1568)
In last one it will add nginx to Jaeger ingress. [List of available ingress controllers](https://docs.google.com/spreadsheets/d/191WWNpjJ2za6-nbG4ZoUMXMpUK8KlCIosvQB0f-oq3k/edit#gid=907731238)

**Comment by iblancasa** [comment]
@rubenvp8510 could you take a look to this PR?

File: pkg/ingress/query.go [hunk 5]
```diff
@@ -150,3 +158,39 @@ func getRule(host string, path string, pathType *networkingv1.PathType, backend
...
+	clientSet, err := kubernetes.NewForConfig(config)
+	if err != nil {
+		return "", err
+	}
+	ingressList, err := clientSet.NetworkingV1().IngressClasses().List(context.Background(), metav1.ListOptions{})
+	if err != nil {
+		return "", err
+	}
+	for _, ingress := range ingressList.Items {
+		if ingress.Name == "nginx" {
```
Comment (rubenvp8510) [inline pkg/ingress/query.go:178]: nit: may be we should put this on a constant

**Comment by rubenvp8510** [comment]
There is an small issue with the linter. and small style comments other than that this LGTM

**Review by rubenvp8510 — APPROVED** [review]
