### PR TITLE
Remove sidecars of annotated namespaces when annotation is deleted

### LINKED ISSUE #906: Agent sidecars are not cleared when annotation is deleted from namespace
Related to https://github.com/jaegertracing/jaeger-operator/pull/897

Steps to reproduce:
```
# go to default namespace
oc create -f deploy/examples/simplest.yaml
oc create deployment vertx --image=jaegertracing/vertx-create-span:operator-e2e-tests

oc annotate namespace default sidecar.jaegertracing.io/inject=true
oc annotate namespace default sidecar.jaegertracing.io/inject-
```

After these steps the agent is vertx deployment is still injected.

cc) @rubenvp8510

### PR DESCRIPTION
**Pull request by rubenvp8510**
Fixes #906 

Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

### CODE REVIEW

File: pkg/controller/namespace/namespace_controller.go [hunk 1]
```diff
@@ -155,6 +155,29 @@ func (r *ReconcileNamespace) Reconcile(request reconcile.Request) (reconcile.Res
 			} else {
 				log.WithField("deployment", dep.Name).Info("No suitable Jaeger instances found to inject a sidecar")
 			}
+		} else {
+			// Don't need injection, may be need to remove the sidecar?
+			// If deployment don't have the annotation and has an agent, this may be injected by the namespace
+			// we need to clean it.
+			agent, _ := inject.HasJaegerAgent(dep)
+			_, depAnnotation := dep.Annotations[inject.Annotation]
```
Comment (jpkrohling) [inline pkg/controller/namespace/namespace_controller.go:163]: `s/depAnnotation/ok` -- you are not getting the annotation, you are getting a boolean on whether it was found.

File: pkg/controller/namespace/namespace_controller.go [hunk 2]
```diff
@@ -155,6 +155,29 @@ func (r *ReconcileNamespace) Reconcile(request reconcile.Request) (reconcile.Res
...
+			if agent && !depAnnotation{
+				jaegerInstance, label := dep.Labels[inject.Label]
```
Comment (jpkrohling) [inline pkg/controller/namespace/namespace_controller.go:165]: Same here.

File: pkg/controller/namespace/namespace_controller.go [hunk 3]
```diff
@@ -155,6 +155,29 @@ func (r *ReconcileNamespace) Reconcile(request reconcile.Request) (reconcile.Res
...
+				if label {
+					log.WithFields(log.Fields{
+						"deployment":       dep.Name,
+						"namespace":        dep.Namespace,
+						"jaeger":           jaegerInstance,
+					}).Info("Removing Jaeger Agent sidecar")
+					inject.CleanSidecar(jaegerInstance, dep)
+					if err := r.client.Update(ctx, dep); err != nil {
```
Comment (jpkrohling) [inline pkg/controller/namespace/namespace_controller.go:173]: Use Patch instead of Update, to reduce the risk of failure. Look at this one for reference: https://github.com/open-telemetry/opentelemetry-operator/issues/54

File: pkg/controller/namespace/namespace_controller.go [hunk 4]
```diff
@@ -157,20 +157,21 @@ func (r *ReconcileNamespace) Reconcile(request reconcile.Request) (reconcile.Res
...
+			_, hasDepAnnotation := dep.Annotations[inject.Annotation]
+			if hasAgent && !hasDepAnnotation {
+				jaegerInstance, hasLabel := dep.Labels[inject.Label]
+				if hasLabel {
 					log.WithFields(log.Fields{
 						"deployment":       dep.Name,
 						"namespace":        dep.Namespace,
 						"jaeger":           jaegerInstance,
 					}).Info("Removing Jaeger Agent sidecar")
+					patch := client.MergeFrom(dep.DeepCopy())
```
Comment (jpkrohling) [inline pkg/controller/namespace/namespace_controller.go:172]: If `dep` is a pointer, you might not need to do a DeepCopy, you can just dereference it.

**Review by jpkrohling — COMMENTED** [review]
LGTM. A minor comment on the `dep.DeepCopy()`, but this looks good. Have you done manual testing of this?

**Comment by rubenvp8510** [comment]
Yes I did manual testing, with the steps detailed in the issue on how to reproduce.
