### PR TITLE
fix sampling strategy file issue in Jaeger Collector

### LINKED ISSUE #696: Override sampling strategy file in Jaeger Collector
I am trying to use sampling strategy with my jaeger collector. I am able to pass the sampling file to the collector and it shows up in the args list. But, the problem is jager-collector always picks up the default (`sampling.strategies-file=/etc/jaeger/sampling/sampling.json`) file. I tried to modify the default file but seems like that's not possible.

```
   Args:
      --kafka.producer.brokers=my-cluster-kafka-brokers.kafka:9092
      --kafka.producer.topic=jaeger-spans
      --log-level=debug
      --sampling.strategies-file=/etc/config/my-sampling.json
      --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
```

Is there any way to make jaeger-collector pick the correct file? 

Below is my jaeger configuration:

```
{
   "apiVersion": "jaegertracing.io/v1",
   "kind": "Jaeger",
   "metadata": {
      "name": "jaeger",
      "namespace": "observability"
   },
   "spec": {
      "agent": {
         "options": {
            "log-level": "debug"
         },
         "strategy": "DaemonSet"
      },
      "collector": {
         "options": {
            "kafka": {
               "producer": {
                  "brokers": "my-cluster-kafka-brokers.kafka:9092",
                  "topic": "jaeger-spans"
               }
            }, 
            "log-level":"debug",
            "sampling.strategies-file": "/etc/config/my-sampling.json"
         },
         "volumeMounts": [
            {
               "name": "config-volume",
               "mountPath": "/etc/config"
            }
         ],
         "volumes": [
            {
               "name": "config-volume",
               "configMap": {
                  "name": "sampling-configmap",
                  "items": [
                     {
                        "key": "my-sampling.json",
                        "path": "keys"
                     }
                  ]
               }
            }
         ]
      },
      "ingester": {
         "options": {
            "ingester": {
               "deadlockInterval": 0
            },
            "kafka": {
               "consumer": {
                  "brokers": "my-cluster-kafka-brokers.kafka:9092",
                  "topic": "jaeger-spans"
               }
            }
         }
      },
      "storage": {
         "cassandraCreateSchema": {
            "datacenter": "cluster",
            "mode": "prod",
            "image": "jaegertracing/jaeger-cassandra-schema:1.14"
         },
         "options": {
            "cassandra": {
               "keyspace": "jaeger_v1_cluster",
               "servers": "10.249.85.166",
            }
         },
         "type": "cassandra"
      },
      "strategy": "streaming"
   }
}
```

### PR DESCRIPTION
**Pull request by shubhanshus**
Resolves #696

### CODE REVIEW

File: pkg/config/sampling/sampling.go [hunk 1]
```diff
@@ -81,6 +82,14 @@ func (u *Config) Get() *corev1.ConfigMap {
 // support for the Sampling configmap.
 func Update(jaeger *v1.Jaeger, commonSpec *v1.JaegerCommonSpec, options *[]string) {
 
+	// Check to validate if sampling strategy file is already passed as an option
```
Comment (objectiser) [inline pkg/config/sampling/sampling.go]: I think the `Get()` function above should also return `nil` (ConfigMap) if the option is explicitly defined, so that an unused config map is not created which might be misleading. So would be better if this check is in a separate function that could also be used in the `Get()` - which would then need to check the options in the `jaeger` arg (from either allInOne or collector node, depending upon the `strategy`).

File: pkg/config/sampling/sampling_test.go [hunk 2]
```diff
@@ -80,3 +79,14 @@ func TestUpdateWithSamplingConfig(t *testing.T) {
 	assert.Len(t, options, 1)
 	assert.Equal(t, "--sampling.strategies-file=/etc/jaeger/sampling/sampling.json", options[0])
 }
+
+func TestUpdateWithSamplingConfigFileOption(t *testing.T) {
+	jaeger := v1.NewJaeger(types.NamespacedName{Name: "TestUpdateWithSamplingConfig"})
```
Comment (objectiser) [inline pkg/config/sampling/sampling_test.go]: nit: the name should be same as the test.

File: pkg/config/sampling/sampling.go (hunk 1 above)
Comment (shubhanshus) [reply pkg/config/sampling/sampling.go]: But, isn't [this statement](https://github.com/jaegertracing/jaeger-operator/blob/fd8a3fa038282c619cc796e7bc4ec9f7e01c10ce/pkg/config/sampling/sampling.go#L33) checking for the sampling options in the Get function? Based on my understanding the `jaeger.Spec.Sampling.Options` is same as the options which we are checking in the update function. Please correct me if my understanding is incorrect.

Comment (objectiser) [reply pkg/config/sampling/sampling.go]: That statement is just checking what content should be placed in the ConfigMap. So it would be possible for someone to specify the sampling config in the Jaeger CR, and still provide an option specifying their own `sampling.strategies-file` parameter - in which case I believe we are allowing the parameter to take precedence.

File: pkg/config/sampling/sampling_test.go (hunk 2 above)
Comment (shubhanshus) [reply pkg/config/sampling/sampling_test.go]: fixed in recent commit.

File: pkg/config/sampling/sampling.go [hunk 3]
```diff
@@ -29,6 +30,9 @@ func (u *Config) Get() *corev1.ConfigMap {
 	var jsonObject []byte
 	var err error
 
+	if CheckForSamplingConfigFile(u.jaeger) {
+		return nil
+	}
 	// Check for empty map
```
Comment (objectiser) [inline pkg/config/sampling/sampling.go]: nit: could you add a line above

File: pkg/config/sampling/sampling.go [hunk 4]
```diff
@@ -77,10 +81,33 @@ func (u *Config) Get() *corev1.ConfigMap {
 	}
 }
 
+// CheckForSamplingConfigFile will check if there is a config file present
+// if there is one it returns true
+func CheckForSamplingConfigFile(jaeger *v1.Jaeger) bool {
+	jsonObject, err := jaeger.Spec.Sampling.Options.MarshalJSON()
```
Comment (objectiser) [inline pkg/config/sampling/sampling.go]: The info at `jaeger.Spec.Sampling.Options` is used to populate the sampling strategies file, when configured via the CR. The `sampling.strategies-file` option would be defined in `jaeger.Spec.AllInOne.Options` or `jaeger.Spec.Collector.Options`, depending on whether the `jaeger.Spec.Strategy` value, e.g.
```
if jaeger.Spec.Strategy == DeploymentStrategyAllInOne {
  options = jaeger.Spec.AllInOne.Options
} else {
  options = jaeger.Spec.Collector.Options
}
```

File: pkg/config/sampling/sampling.go (hunk 3 above)
Comment (shubhanshus) [reply pkg/config/sampling/sampling.go]: fixed in recent commit

File: pkg/config/sampling/sampling.go (hunk 4 above)
Comment (shubhanshus) [reply pkg/config/sampling/sampling.go]: fixed in recent commit

**Comment by shubhanshus** [comment]
Looks like there was an error while verifying licenses from the https://download.docker.com/linux/ubuntu repository. Is there a way by which we can re-run all the tests again?

File: pkg/config/sampling/sampling.go [hunk 5]
```diff
@@ -77,10 +82,42 @@ func (u *Config) Get() *corev1.ConfigMap {
...
+	options := v1.Options{}
+
+	// check for deployment strategy
+	if jaeger.Spec.Strategy == v1.DeploymentStrategyAllInOne {
+		options = jaeger.Spec.AllInOne.Options
+	} else {
+		options = jaeger.Spec.Collector.Options
+	}
+
+	jsonObject, err := options.MarshalJSON()
```
Comment (objectiser) [inline pkg/config/sampling/sampling.go]: Sorry should have picked up on this earlier, but there is a more direct way to test if the option has been defined when using the options, e.g.
```
if _, exists := options["sampling.strategies-file"]; exists {
     ....
     return true
}
```

**Comment by objectiser** [comment]
Thanks!
